//! Apple SDK: MathCoreFFI.xcframework (iOS device, iOS simulator, macOS),
//! the MathCore Swift package around it, a SwiftPM manifest for releases and
//! a CocoaPods spec.

use crate::util::*;

const TARGETS: &[&str] = &[
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-ios",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
];

const RELEASE_URL: &str = "https://github.com/AHAariyan/latex_rendering_engine/releases/download";

pub fn build(verify: bool) -> Result {
    if !cfg!(target_os = "macos") {
        return Err("the Apple SDK builds on macOS with Xcode".into());
    }
    require("xcodebuild", "install Xcode")?;
    let version = version();
    let out = dist().join("apple");
    reset_dir(&out)?;

    step("Apple: static libraries for every slice");
    rustup_targets(TARGETS)?;
    for t in TARGETS {
        cargo_sdk_build("mathffi", Some(t))?;
    }
    let lib = |t: &str| sdk_out(Some(t)).join("libmathcore_ffi.a");
    let work = root().join("target/sdk-apple");
    reset_dir(&work)?;
    for (name, parts) in [
        ("ios", vec!["aarch64-apple-ios"]),
        ("ios-sim", vec!["aarch64-apple-ios-sim", "x86_64-apple-ios"]),
        ("macos", vec!["aarch64-apple-darwin", "x86_64-apple-darwin"]),
    ] {
        let dir = work.join(name);
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let mut c = cmd("lipo");
        c.arg("-create");
        for p in parts {
            c.arg(lib(p));
        }
        run(c.arg("-output").arg(dir.join("libmathcore_ffi.a")))?;
        // Debug info only; the symbols the linker needs stay.
        run(cmd("strip").arg("-S").arg(dir.join("libmathcore_ffi.a")))?;
    }
    let headers = work.join("headers");
    copy(&root().join("crates/mathffi/include/mathcore.h"), &headers.join("mathcore.h"))?;
    copy(
        &root().join("platforms/ios/MathCore/Sources/CMathCore/include/module.modulemap"),
        &headers.join("module.modulemap"),
    )?;

    step("Apple: MathCoreFFI.xcframework");
    let xcf = out.join("MathCoreFFI.xcframework");
    let mut c = cmd("xcodebuild");
    c.arg("-create-xcframework");
    for slice in ["ios", "ios-sim", "macos"] {
        c.arg("-library")
            .arg(work.join(slice).join("libmathcore_ffi.a"))
            .arg("-headers")
            .arg(&headers);
    }
    run(c.arg("-output").arg(&xcf))?;
    // The in-repo Swift package builds against a local copy.
    let local = root().join("platforms/ios/MathCore/MathCoreFFI.xcframework");
    if local.exists() {
        std::fs::remove_dir_all(&local).map_err(|e| e.to_string())?;
    }
    copy_dir(&xcf, &local)?;

    step("Apple: release archive, checksum, manifests");
    let zip = out.join("MathCoreFFI.xcframework.zip");
    run(cmd("ditto")
        .args(["-c", "-k", "--sequesterRsrc", "--keepParent"])
        .arg(&xcf)
        .arg(&zip))?;
    let checksum = output(cmd("swift").args(["package", "compute-checksum"]).arg(&zip))?;
    write(&out.join("Package.swift"), &package_manifest(&version, &checksum))?;
    write(&out.join("MathCore.podspec"), &podspec(&version))?;
    copy_dir(
        &root().join("platforms/ios/MathCore/Sources/MathCore"),
        &out.join("Sources/MathCore"),
    )?;
    write(&out.join("checksum.txt"), &format!("{checksum}\n"))?;
    // CocoaPods takes one archive with the sources, the framework and the license.
    copy(&root().join("LICENSE"), &out.join("LICENSE")).or_else(|_| write(&out.join("LICENSE"), "MIT\n"))?;
    run(cmd("zip")
        .args([
            "-qry",
            &format!("MathCore-apple-{version}.zip"),
            "MathCoreFFI.xcframework",
            "Sources",
            "MathCore.podspec",
            "LICENSE",
        ])
        .current_dir(&out))?;

    if verify {
        step("Apple: tests on macOS");
        let pkg = root().join("platforms/ios/MathCore");
        run(cmd("swift").arg("test").current_dir(&pkg))?;
        for dest in ["generic/platform=iOS Simulator", "generic/platform=iOS"] {
            step(&format!("Apple: build for {dest}"));
            run(cmd("xcodebuild")
                .args(["-quiet", "-scheme", "MathCore", "-destination", dest, "-derivedDataPath"])
                .arg(root().join("target/xcode"))
                .arg("build")
                .current_dir(&pkg))?;
        }
    }
    eprintln!("\nApple SDK {version} in {}\n  checksum {checksum}", out.display());
    Ok(())
}

/// The root `Package.swift` a release commits, so `.package(url: <repo>,
/// from: "<version>")` resolves to the prebuilt binary on the release page.
pub fn package_manifest(version: &str, checksum: &str) -> String {
    format!(
        r#"// swift-tools-version:5.9
// Generated by `cargo xtask sdk apple` for release {version}. Do not edit.
import PackageDescription

let package = Package(
    name: "MathCore",
    platforms: [.iOS(.v13), .macOS(.v11)],
    products: [
        .library(name: "MathCore", targets: ["MathCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "MathCoreFFI",
            url: "{RELEASE_URL}/v{version}/MathCoreFFI.xcframework.zip",
            checksum: "{checksum}"
        ),
        .target(name: "MathCore", dependencies: ["MathCoreFFI"], path: "platforms/ios/MathCore/Sources/MathCore"),
    ]
)
"#
    )
}

fn podspec(version: &str) -> String {
    format!(
        r#"Pod::Spec.new do |s|
  s.name             = 'MathCore'
  s.version          = '{version}'
  s.summary          = 'Native TeX math typesetting for iOS and macOS. No WebView.'
  s.description      = 'TeX, AsciiMath and chemistry (mhchem) typeset natively from the OpenType MATH table, with VoiceOver speech and sub-expression navigation.'
  s.homepage         = 'https://github.com/AHAariyan/latex_rendering_engine'
  s.license          = {{ :type => 'MIT' }}
  s.author           = 'mathcore'
  s.source           = {{ :http => '{RELEASE_URL}/v{version}/MathCore-apple-{version}.zip' }}
  s.ios.deployment_target = '13.0'
  s.osx.deployment_target = '11.0'
  s.swift_version    = '5.9'
  s.source_files     = 'Sources/MathCore/**/*.swift'
  s.vendored_frameworks = 'MathCoreFFI.xcframework'
end
"#
    )
}
