//! Apple SDK: MathCoreFFI.xcframework (iOS device, iOS simulator, macOS),
//! the MathCore Swift package around it, a SwiftPM manifest for releases and
//! a CocoaPods spec.

use crate::util::*;

const TARGETS: &[&str] = &[
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-ios",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
];

const RELEASE_URL: &str = "https://github.com/AHAariyan/latex_rendering_engine/releases/download";

pub fn build(verify: bool) -> Result {
    if !cfg!(target_os = "macos") {
        return Err("the Apple SDK builds on macOS with Xcode".into());
    }
    require("xcodebuild", "install Xcode")?;
    let version = version();
    let out = dist().join("apple");
    reset_dir(&out)?;

    step("Apple: static libraries for every slice");
    rustup_targets(TARGETS)?;
    for t in TARGETS {
        cargo_sdk_build("mathffi", Some(t))?;
    }
    let lib = |t: &str| sdk_out(Some(t)).join("libmathcore_ffi.a");
    let work = root().join("target/sdk-apple");
    reset_dir(&work)?;
    for (name, parts) in [
        ("ios", vec!["aarch64-apple-ios"]),
        ("ios-sim", vec!["aarch64-apple-ios-sim", "x86_64-apple-ios"]),
        ("macos", vec!["aarch64-apple-darwin", "x86_64-apple-darwin"]),
    ] {
        let dir = work.join(name);
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let mut c = cmd("lipo");
        c.arg("-create");
        for p in parts {
            c.arg(lib(p));
        }
        run(c.arg("-output").arg(dir.join("libmathcore_ffi.a")))?;
        // Debug info only; the symbols the linker needs stay.
        run(cmd("strip").arg("-S").arg(dir.join("libmathcore_ffi.a")))?;
    }
    let headers = work.join("headers");
    copy(&root().join("crates/mathffi/include/mathcore.h"), &headers.join("mathcore.h"))?;
    copy(
        &root().join("platforms/ios/MathCore/Sources/CMathCore/include/module.modulemap"),
        &headers.join("module.modulemap"),
    )?;

    step("Apple: MathCoreFFI.xcframework");
    let xcf = out.join("MathCoreFFI.xcframework");
    let mut c = cmd("xcodebuild");
    c.arg("-create-xcframework");
    for slice in ["ios", "ios-sim", "macos"] {
        c.arg("-library")
            .arg(work.join(slice).join("libmathcore_ffi.a"))
            .arg("-headers")
            .arg(&headers);
    }
    run(c.arg("-output").arg(&xcf))?;
    // The in-repo Swift package builds against a local copy.
    let local = root().join("platforms/ios/MathCore/MathCoreFFI.xcframework");
    if local.exists() {
        std::fs::remove_dir_all(&local).map_err(|e| e.to_string())?;
    }
    copy_dir(&xcf, &local)?;

    step("Apple: release archive, checksum, manifests");
    let zip = out.join("MathCoreFFI.xcframework.zip");
    run(cmd("ditto")
        .args(["-c", "-k", "--sequesterRsrc", "--keepParent"])
        .arg(&xcf)
        .arg(&zip))?;
    let checksum = output(cmd("swift").args(["package", "compute-checksum"]).arg(&zip))?;
    write(&out.join("Package.swift"), &package_manifest(&version, &checksum))?;
    write(&out.join("MathCore.podspec"), &podspec(&version))?;
    copy_dir(
        &root().join("platforms/ios/MathCore/Sources/MathCore"),
        &out.join("Sources/MathCore"),
    )?;
    write(&out.join("checksum.txt"), &format!("{checksum}\n"))?;
    // CocoaPods takes one archive with the sources, the framework and the license.
    copy(&root().join("LICENSE"), &out.join("LICENSE")).or_else(|_| write(&out.join("LICENSE"), "MIT\n"))?;
    run(cmd("zip")
        .args([
            "-qry",
            &format!("MathCore-apple-{version}.zip"),
            "MathCoreFFI.xcframework",
            "Sources",
            "MathCore.podspec",
            "LICENSE",
        ])
        .current_dir(&out))?;

    if verify {
        step("Apple: tests on macOS");
        let pkg = root().join("platforms/ios/MathCore");
        run(cmd("swift").arg("test").current_dir(&pkg))?;
        for dest in ["generic/platform=iOS Simulator", "generic/platform=iOS"] {
            step(&format!("Apple: build for {dest}"));
            run(cmd("xcodebuild")
                .args(["-quiet", "-scheme", "MathCore", "-destination", dest, "-derivedDataPath"])
                .arg(root().join("target/xcode"))
                .arg("build")
                .current_dir(&pkg))?;
        }
    }
    eprintln!("\nApple SDK {version} in {}\n  checksum {checksum}", out.display());
    Ok(())
}

/// The root `Package.swift` a release commits, so `.package(url: <repo>,
/// from: "<version>")` resolves to the prebuilt binary on the release page.
pub fn package_manifest(version: &str, checksum: &str) -> String {
    format!(
        r#"// swift-tools-version:5.9
// Generated by `cargo xtask sdk apple` for release {version}. Do not edit.
import PackageDescription

let package = Package(
    name: "MathCore",
    platforms: [.iOS(.v13), .macOS(.v11)],
    products: [
        .library(name: "MathCore", targets: ["MathCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "MathCoreFFI",
            url: "{RELEASE_URL}/v{version}/MathCoreFFI.xcframework.zip",
            checksum: "{checksum}"
        ),
        .target(name: "MathCore", dependencies: ["MathCoreFFI"], path: "platforms/ios/MathCore/Sources/MathCore"),
    ]
)
"#
    )
}

fn podspec(version: &str) -> String {
    format!(
        r#"Pod::Spec.new do |s|
  s.name             = 'MathCore'
  s.version          = '{version}'
  s.summary          = 'Native TeX math typesetting for iOS and macOS. No WebView.'
  s.description      = 'TeX, AsciiMath and chemistry (mhchem) typeset natively from the OpenType MATH table, with VoiceOver speech and sub-expression navigation.'
  s.homepage         = 'https://github.com/AHAariyan/latex_rendering_engine'
  s.license          = {{ :type => 'MIT' }}
  s.author           = 'mathcore'
  s.source           = {{ :http => '{RELEASE_URL}/v{version}/MathCore-apple-{version}.zip' }}
  s.ios.deployment_target = '13.0'
  s.osx.deployment_target = '11.0'
  s.swift_version    = '5.9'
  s.source_files     = 'Sources/MathCore/**/*.swift'
  s.vendored_frameworks = 'MathCoreFFI.xcframework'
end
"#
    )
}

/// Wraps the engine's iOS and macOS dynamic libraries as frameworks in one
/// xcframework, for hosts that load it by name (Flutter) or import it from
/// Swift (React Native). A dynamic framework survives the symbol stripping of
/// release builds, which a static library linked into the app does not. Returns its path under target/.
pub fn dynamic_xcframework(version: &str, platform: ApplePlatform) -> Result<std::path::PathBuf> {
    let targets = [
        "aarch64-apple-ios",
        "aarch64-apple-ios-sim",
        "x86_64-apple-ios",
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
    ];
    rustup_targets(&targets)?;
    for t in targets {
        cargo_sdk_build("mathffi", Some(t))?;
    }
    let work = root().join("target/sdk-dynamic-apple").join(platform.name());
    reset_dir(&work)?;
    let mut frameworks = Vec::new();
    // One platform per xcframework: CocoaPods classifies a framework by all
    // of its slices and refuses a mix it cannot tell apart.
    let slices: Vec<(&str, Vec<&str>, bool)> = match platform {
        ApplePlatform::Ios => vec![
            ("ios", vec!["aarch64-apple-ios"], false),
            ("ios-sim", vec!["aarch64-apple-ios-sim", "x86_64-apple-ios"], false),
        ],
        ApplePlatform::MacOs => vec![("macos", vec!["aarch64-apple-darwin", "x86_64-apple-darwin"], true)],
    };
    for (slice, parts, macos) in slices {
        let fw = work.join(slice).join("MathCoreFFI.framework");
        // macOS frameworks are versioned bundles; iOS ones are flat.
        let (bin_dir, plist_dir, install) = if macos {
            (
                fw.join("Versions/A"),
                fw.join("Versions/A/Resources"),
                "@rpath/MathCoreFFI.framework/Versions/A/MathCoreFFI",
            )
        } else {
            (fw.clone(), fw.clone(), "@rpath/MathCoreFFI.framework/MathCoreFFI")
        };
        std::fs::create_dir_all(&plist_dir).map_err(|e| e.to_string())?;
        let mut c = cmd("lipo");
        c.arg("-create");
        for p in &parts {
            c.arg(sdk_out(Some(p)).join("libmathcore_ffi.dylib"));
        }
        run(c.arg("-output").arg(bin_dir.join("MathCoreFFI")))?;
        run(cmd("install_name_tool").args(["-id", install]).arg(bin_dir.join("MathCoreFFI")))?;
        write(&plist_dir.join("Info.plist"), &info_plist(version, macos))?;
        // Headers and a module map, so Swift can `import MathCoreFFI`.
        let (headers, modules) = if macos {
            (fw.join("Versions/A/Headers"), fw.join("Versions/A/Modules"))
        } else {
            (fw.join("Headers"), fw.join("Modules"))
        };
        copy(&root().join("crates/mathffi/include/mathcore.h"), &headers.join("mathcore.h"))?;
        write(
            &modules.join("module.modulemap"),
            "framework module MathCoreFFI {\n  umbrella header \"mathcore.h\"\n  export *\n  module * { export * }\n}\n",
        )?;
        if macos {
            run(cmd("ln").args(["-sfh", "A", "Versions/Current"]).current_dir(&fw))?;
            run(cmd("ln")
                .args(["-sfh", "Versions/Current/MathCoreFFI", "MathCoreFFI"])
                .current_dir(&fw))?;
            run(cmd("ln").args(["-sfh", "Versions/Current/Resources", "Resources"]).current_dir(&fw))?;
            run(cmd("ln").args(["-sfh", "Versions/Current/Headers", "Headers"]).current_dir(&fw))?;
            run(cmd("ln").args(["-sfh", "Versions/Current/Modules", "Modules"]).current_dir(&fw))?;
        }
        frameworks.push(fw);
    }
    let xcf = work.join("MathCoreFFI.xcframework");
    let mut c = cmd("xcodebuild");
    c.arg("-create-xcframework");
    for fw in &frameworks {
        c.arg("-framework").arg(fw);
    }
    run(c.arg("-output").arg(&xcf))?;
    Ok(xcf)
}

fn info_plist(version: &str, macos: bool) -> String {
    let min = if macos {
        "<key>LSMinimumSystemVersion</key><string>10.14</string>"
    } else {
        "<key>MinimumOSVersion</key><string>13.0</string>"
    };
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleExecutable</key><string>MathCoreFFI</string>
  <key>CFBundleIdentifier</key><string>dev.mathcore.MathCoreFFI</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>MathCoreFFI</string>
  <key>CFBundlePackageType</key><string>FMWK</string>
  <key>CFBundleShortVersionString</key><string>{version}</string>
  <key>CFBundleVersion</key><string>{version}</string>
  {min}
</dict>
</plist>
"#
    )
}

#[derive(Clone, Copy)]
pub enum ApplePlatform {
    Ios,
    MacOs,
}

impl ApplePlatform {
    fn name(self) -> &'static str {
        match self {
            ApplePlatform::Ios => "ios",
            ApplePlatform::MacOs => "macos",
        }
    }
}
